[package]
name = "analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.26.1", features = ["lazy", "temporal", "describe", "json", "parquet", "dtype-datetime"] }
serde = { version = "1.0.204", features = ["derive"] }
